name: npm auto deprecate
on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:
jobs:
  npm-auto-deprecate:
    name: npm auto deprecate
    runs-on: ubuntu-latest
    if: github.repository_owner == 'cyberpurge-net'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install node.js v18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        uses: ./packages/actions/src/yarnCache

      - name: Deprecate versions
        run: 'yarn npm-deprecate --name "*dev*" --package @cyberpurge-net/brokers @cyberpurge-net/builders @cyberpurge-net/collection @cyberpurge-net/core @cyberpurge-net/formatters discord.js @cyberpurge-net/next @cyberpurge-net/proxy @cyberpurge-net/rest @cyberpurge-net/util @cyberpurge-net/voice @cyberpurge-net/ws'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
