name: Publish dev
on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:
jobs:
  npm-publish:
    name: npm publish
    strategy:
      fail-fast: false
      matrix:
        include:
          - package: '@cyberpurge-net/brokers'
            folder: 'brokers'
          - package: '@cyberpurge-net/builders'
            folder: 'builders'
          - package: '@cyberpurge-net/collection'
            folder: 'collection'
          - package: '@cyberpurge-net/core'
            folder: 'core'
          - package: '@cyberpurge-net/formatters'
            folder: 'formatters'
          - package: 'discord.js'
            folder: 'discord.js'
          - package: '@cyberpurge-net/next'
            folder: 'next'
          - package: '@cyberpurge-net/proxy'
            folder: 'proxy'
          - package: '@cyberpurge-net/rest'
            folder: 'rest'
          - package: '@cyberpurge-net/util'
            folder: 'util'
          - package: '@cyberpurge-net/voice'
            folder: 'voice'
          - package: '@cyberpurge-net/ws'
            folder: 'ws'
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
    if: github.repository_owner == 'cyberpurge-net'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install node.js v18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        uses: ./packages/actions/src/yarnCache

      - name: Build dependencies
        run: yarn build

      - name: Publish package
        run: |
          yarn workspace ${{ matrix.package }} release --preid "dev.$(date +%s)-$(git rev-parse --short HEAD)"
          yarn workspace ${{ matrix.package }} npm publish --tag dev || true
        env:
          YARN_NPM_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
